EMERGENCY_KEYWORDS = [
    "death",
    "dismemberment",
    "eye",
    "limb",
    "urgent help",
]

COMPETITORS = [
    # Global region
    "caa",
    "allianz",
    "sun life",
    "desjardins",
    "td insurance",
    "tugo",
    "seven corners",
    "world nomads",
    "travel guard",
    "aig",
    "travelex",
    "axa",
    "berkshire hathaway",
    "img",
    "internacional medical group",
    "generali",
    "tin leg",
    "travel insured",
    "arch roamright",
    "cigna",
    "bupa",
    "tokio marine",
    "zurich",
    "american express",
    "nationwide",
    "travelsafe",
    "hanse merkur",
    
    # Asian region
    "manulife",
    "pacific cross",
    "chubb",
    "msh international",
    "april international",
    "vumi",
    "acs",
    "worldtrips",
    "safetywing",
    "trip.com",
    "cover for you",
    "hsbc",
    "blue cross",
    "mox bank",
    "qbe",
    "asia insurance",
    "bowtie",
    "avo",
    "onedegree",
    "za insurance"
]